// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Student_IMS.Data;

#nullable disable

namespace Student_IMS.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20230703120206_some_students")]
    partial class some_students
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Student_IMS.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Name = "John",
                            StudentNumber = 123456,
                            Surname = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Age = 21,
                            Name = "Jane",
                            StudentNumber = 654321,
                            Surname = "Doe"
                        },
                        new
                        {
                            Id = 3,
                            Age = 22,
                            Name = "John",
                            StudentNumber = 123654,
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = 4,
                            Age = 23,
                            Name = "Jane",
                            StudentNumber = 321654,
                            Surname = "Smith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
